### ISSUE TITLE
PR to Homebrew

### ISSUE THREAD

**Issue by ear** [caius/homebrew-jo#5]
Hello, thank you for making this.

I wonder if there is a deeper reason for this to be a tap instead of a straight pull-request into homebrew's Formulae repository than the wait period for it to be reviewed.

Do you already know it won't be accepted for some reason? If not, have you considered turning this into a PR? I think it would make the program much more discoverable if it appeared in the search results!

I was about to do it myself but I thought I'd ask you when I found your repository.

**Comment by jpmens** [comment]
As `jo`'s author, I'd like to see `jo` in Homebrew's Formulae repository, so if either of you can make it happen, I'm all for it. :-)

**Comment by caius** [comment]
Ooh, good question! Initially it was due to there not being stable tagged
releases, but there are now so there's no technical reason blocking it. I
was intending on submitting the the formula upstream to the main homebrew
repository, just haven't done so yet.

If anyone else fancies pushing it up, please feel free. Otherwise I'll do
it at some point 🙃

C
---
Caius Durling
Transmitted from my handheld supercomputer
caius@caius.name
+44 (0) 7960 268 100
http://caius.name/

On 13 Mar 2016, at 13:20, JP Mens <notifications@github.com> wrote:

As jo's author, I'd like to see jo in Homebrew's Formulae repository, so if
either of you can make it happen, I'm all for it. :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/caius/homebrew-jo/issues/5#issuecomment-195956247>.

**Comment by jpmens** [comment]
@ear go ahead then please, and when it's in Homebrew would you ping me so I change `jo`'s README?

**Comment by ear** [comment]
@jpmens I'm on it

**Comment by ear** [comment]
Added: Homebrew/homebrew#50074

**Comment by jpmens** [comment]
@ear thank you

**Comment by jpmens** [comment]
@caius thank you for the initial homebrew formula, and @ear thank you for pushing into Homebrew's official Formulae. I have just found `jo` there, so I'll close this now.

@caius I'm not sure what the polite way of saying this is, but I assume you can delete this repository? :-)
